#!/usr/bin/env bash
# Displays "Best school" using the while loop and prints "Hi" on the 9th iteration

i=0

while (( i < 10 ))
do
	if (( i == 9 ))
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++  ))
done
