#!/usr/bin/env bash
# Displays the time from 0 to 12:59

hour=0
minutes=1

while (( hour <= 12 ))
do
	echo "Hour: $hour"
	while (( minutes <= 59 ))
	do
		echo $minutes
		(( minutes++ ))
	done
	minutes=1
	(( hour++ ))
done
